### ISSUE TITLE
Ответ на уловку 

### ISSUE THREAD

**Issue by cantylv** [frontend-park-mail-ru/homework_2024_1#48]
а тут я тебя немного подловила))) ты убрал первый пустой объект и сделал функцию не чистой - почему?))

подловили! я сделал ее не чистой, потому что объекты могут изменяться в функциях, а примитивные типы данных: число, строка - не меняются (в функции создается их копия). поэтому мы попортим objects[0], если таковой будет

**Comment by DPeshkoff** [comment]
Кажется, это сюда попало случайно из PR'а)

**Comment by cantylv** [comment]
Да :D
